### ISSUE TITLE
0.3.4在vite2.9.15下打包失败

### ISSUE THREAD

**Issue by komaedaXnagito** [antvis/attr#12]
* **Link**:
* **Platform**:
* **Mini Showcase(like screenshots)**:

报错日志：
 [plugin vite:dep-pre-bundle] Failed to resolve entry for package "@antv/attr". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "@antv/attr". The package may have incorrect main/module/exports specified in its package.json.

使用的是ice.js 2.6.6 引入了4.1.22的bizcharts

**Comment by Superman-wc** [comment]
vite 4.2.1 下打包也是失败的
```
 [commonjs--resolver] Failed to resolve entry for package "@antv/attr". The package may have incorrect main/module/exports specified in its package.json.
bi:build: error during build:
bi:build: Error: Failed to resolve entry for package "@antv/attr". The package may have incorrect main/module/exports specified in its package.json.
bi:build:     at packageEntryFailure (file:///Users/superman/studio/bi/bi-datasource/node_modules/vite/dist/node/chunks/dep-79892de8.js:23266:11)
bi:build:     at resolvePackageEntry (file:///Users/superman/studio/bi/bi-datasource/node_modules/vite/dist/node/chunks/dep-79892de8.js:23263:5)
bi:build:     at tryNodeResolve (file:///Users/superman/studio/bi/bi-datasource/node_modules/vite/dist/node/chunks/dep-79892de8.js:23000:20)
bi:build:     at Object.resolveId (file:///Users/superman/studio/bi/bi-datasource/node_modules/vite/dist/node/chunks/dep-79892de8.js:22762:28)
bi:build:     at file:///Users/superman/studio/bi/bi-datasource/node_modules/rollup/dist/es/shared/node-entry.js:24349:40
bi:build:     at async PluginDriver.hookFirstAndGetPlugin (file:///Users/superman/studio/bi/bi-datasource/node_modules/rollup/dist/es/shared/node-entry.js:24249:28)
bi:build:     at async resolveId (file:///Users/superman/studio/bi/bi-datasource/node_modules/rollup/dist/es/shared/node-entry.js:23186:26)
bi:build:     at async ModuleLoader.resolveId (file:///Users/superman/studio/bi/bi-datasource/node_modules/rollup/dist/es/shared/node-entry.js:23450:15)
bi:build:     at async Object.resolveId (file:///Users/superman/studio/bi/bi-datasource/node_modules/vite/dist/node/chunks/dep-79892de8.js:8006:10)
bi:build:     at async PluginDriver.hookFirstAndGetPlugin (file:///Users/superman/studio/bi/bi-datasource/node_modules/rollup/dist/es/shared/node-entry.js:24249:28)
bi:build: error Command failed with exit code 1.
```

**Comment by araratmartirossyan** [comment]
Have same issue, is it fixed?

**Comment by Superman-wc** [comment]
目前我的处理方式是
主项目下使用0.3.3版本的包，`yarn install @antv/attr@0.3.3`
删除G2内部引用的依赖包 `rm -rf node_modules/@antv/g2/node_modules/@antv/attr`
G2使用4.2.5的版本
可以正常编译通过

**Comment by PDieE** [comment]
在 package.json 内将 @antv/attr 锁定到 0.3.3 即可，估计是G2 5.x发布了所以 @antv/attr 升级了 但是 4.x又不支持又没锁
